export default [
    `A tiny brass clockwork cathedral that plays organ music when wound`,
    `A bag of one-hundred marbles, ninety-nine are white and the last is black`,
    `A roc's feather`,
    `A soldier doll of a long-forgotten empire`,
    `A small mechanical snapping turtle`,
    `A piece of torn red cloth bearing a royal insignia`,
    `A preserved eyeball attached to a spindly eye-stalk, the nerves twitch occasionally`,
    `A shrunken head`,
    `A ransom note for a long-lost relative of yours`,
    `An hourglass filled with glowing sand that falls slower or faster than it should`,
    `An obsidian icon of a forgotten deity`,
    `A recorder carved from brilliant white ash`,
    `A scroll case and scroll inscribed with an unfinished spell`,
    `A small stone that shifts through the color spectrum over the course of a week`,
    `A candle whose flame produces no heat, can't be extinguished nor transfer its flame`,
    `A leather necklace lined with troll fangs`,
    `A small piece of gelatinous cube that slightly stings the skin, prolonged exposure can cause a rash`,
    `A hefty piece of magnetic ore that fell from the skies`,
    `A mining pick made from bone`,
    `A coin that appears to have the same image on both sides to everyone except you`,
    `A bag full of tiny mummified frogs`,
    `A box containing a mold for a cast iron key`,
    `A compass that always points to where you were a day ago`,
    `A painting of yourself as you would be when much older`,
    `A small jewelry box containing three perfectly round and smooth stones`,
    `A wanted poster with your face but someone else's name`,
    `A wooden coin that weighs and sounds like metal`,
    `A tiny soapstone octopus that slowly absorbs water`,
    `A glass lamp with a tiny star suspended inside`,
    `A petrified heart that leaks an oily black substance`,
    `A harp with stings that play notes you can only hear after sunset`,
    `A pair of old books written in a lost language`,
    `A map with a large patch of ocean torn out`,
    `A pair of tetrahedral clay dice that always add up to five when rolled together`,
    `A pair of glasses that make you invisible to yourself`,
    `A small frozen glass-like flame that melts and refreezes, morphing over time`,
    `A pewter ring with an inlaid gold band that slowly rotates`,
    `A hand mirror that shows everyone's reflection except your own`,
    `A horn that when blown through produces silence`,
    `A freshly-excavated humanoid skeleton the size of your hand`,
    `A broken sword hilt with strange runes on the remains of the blade`,
    `A crow's claw`,
    `A thin metal rod that plays out a tune when repeatedly tapped`,
    `A heavy metal coin that floats on water`,
    `A glass bone`,
    `A bouncing ball made of a strange spongy wood`,
    `A small crate box filled with burlap sacks of different exotic coffee beans`,
    `A small mass of grey metallic ooze that can be stretched but not pulled apart`,
    `A letter from a relative addressing you by a different name`,
    `A stone statue of a god with an creature's head`,
    `A small piece of rock that floats almost a hair's-breadth above the ground`,
    `A dagger, simple and sharp, that is incapable of hurting it's wielder`,
    `A pair of copper snake earrings of elven design`,
    `A very small and furry creature that always sleeps and never eats`,
    `A grime encrusted bone ring`,
    `A "magical" acorn`,
    `A green leather pouch full of berries that will never rot`,
    `A silver and glass inkwell that cannot spill`,
    `A child's diary`,
    `A cloak lined with a strange blue fur`,
    `A small crystal sphere that illuminates under starlight`,
    `A pocket-sized, clockwork gizmo that forecasts severe winds and rain coming your way`,
    `A hand sized bell with no clapper but it still rings when shaken`,
    `The right arm broken off from a statue`,
    `A glass bottle that spins and points to the same place`,
    `An antique sword, rusted and seized within its scabbard`,
    `A strange barbed choker that makes your voice more resonant`,
    `A small piece of fabric that still holds the scent of a lost love`,
    `A rock with a patch of curious purple moss`,
    `A wooden carving of a strange unknown beast`,
    `A spherical astrolabe that tracks the movements of the planes`,
    `An ivory hair comb that changes your hair color subtly after repeated use`,
    `A razor-sharp piece of metal wrapped in a bloody bandage`,
    `A heavy rust-covered metal rod that whispers words only you hear`,
    `A slender wooden twig which cannot be broken by any man`,
    `A hand puppet that very much resembles another party member`,
    `A wooden leg with a hidden compartment`,
    `A clay teapot that fills itself with fresh hot tea every morning`,
    `A small rabbit-fur pouch filled with ceremonial herbs and incense`,
    `A piece of volcanic rock that has never completely cooled down`,
    `A tiny origami spider that occasionally skitters about on its own`,
    `A small dark glass corked bottle filled to the brim with a powerful liquor`,
    `A piece of a castle wall with a map chalked onto one side`,
    `A small pouch of ashes that will remove ink from the pages they are smeared on`,
    `A pocket-watch that started running backwards the moment you picked it up`,
    `A rope belt that can extend to fifty feet`,
    `A rare copy and translation of a religious manuscript`,
    `A magical signet-ring that leaves a seal in wax that only the person or people you designate can see`,
    `A gnarled walking staff of living wood that can manipulate tiny objects while you hold it`,
    `A perfect forgery of a small masterpiece work of art`,
    `A pair of magically linked bits of gemstone, holding one lets you sense the direction of the other`,
    `A tuning fork that produces the most satisfying note anyone that hears it has ever heard`,
    `A musical washboard made of monster bones`,
    `A merchant's scale you can adjust with a handwave to weigh slightly in your favor`,
    `A necklace of varying spherical and odd-shaped shimmering stones that gives the wearer prophetic dreams`,
    `A quiver of twenty arrows that degrade quickly after impact, leaving no trace`,
    `A small log that burns as hot as a roaring campfire and never turns to ash`,
    `An unfinished autobiography`,
    `A large piece of shell from a dragon's egg`,
    `A needle that becomes immovable when the command word is spoken (You don't know the command word)`,
    `A horn made of ivory, instead of sound it produces wind`,
    `A pair of stone sandals, they are more comfortable than any shoes you've ever worn`,
    `A small flat stone that sticks to whatever it touches (DC 5 STR to remove it)`,
    `A piece of twine that when plucked produces a low tone and continues to resonate while the twine is held taught`,
    `A pair of leather gloves, when worn you can not touch anything with them`,
    `A obsidian comb that makes hair curlier when used`,
    `A marble that rolls away from you and towards the nearest individual of your species`,
    `A small mouse that can talk to you with telepathy (DC 10 animal handling to befriend it, or it shouts obscenities in your mind)`,
    `A thimble that cannot be crushed by any means`,
    `A flagon that constantly sweats ale`,
    `A flask that can capture any scent when the command word is spoken, and the release it when it's spoken again (You know the command word)`,
    `A pair of goggles that look stylish on only you`,
    `A trio of small metal balls that vibrate when all three are touched together`,
    `A glass bottle with two openings, things can only go through one end and out the other`,
    `A small drum that beats in time with your heart`,
    `A glass finger that causes painful headaches when in your possession for more than 24 hours`,
    `A beret that when worn causes peasants to refer to you as colonel`,
    `A loincloth that ripples gently as if it was always in the wind`,
    `A coin purse that sounds and feels like it's filled, but is not`,
    `A quill pen that can write in the air (Requires ink and lasts 24 hours)`,
    `A piece of paper that writes back to you when you ask it questions`,
    `A roc talon that grips objects and never lets go until the command word is spoken (You don't know the command word)`,
    `A leaf that is perpetually on fire, the flame cannot spread and illuminates an area of 10ft`,
    `A locket with a picture of a person you vaguely remember, each time you open it the picture is different`,
    `A glass orb with a tiny dragon in it, the glass orb can not be broken in any manner, the dragon cannot die, but the dragon is aware of its surroundings and can speak`,
    `A feather that is hot to the touch`,
    `A vial of viscous blue liquid, when poured out the liquid slowly creeps back into the vial`,
    `A potion that changes your gender for 24 hours (You don't know what it does, and no one can identify it)`,
    `A cotton ball that laughs when no one is around`,
    `A ring that always feels cold to the touch, when you wear it you can hear whispers from a distant being`,
    `A scale from a wyvern that when thrown always returns to you`,
    `The feather of a angel, when shaken it produces a brilliant gold dust, this dust is highly addictive`,
    `A small tree in a pot, each day the tree grows a single fruit, every 10 days the fruit changes`,
    `A stool that follows you where ever you go`,
    `A gear that slowly spins of it's own accord`,
    `A wooden carving that is shaped like your mother, it changes shape for whoever holds it`,
    `A holy symbol made from a strange bone, it makes no sound, and you cannot immediately identify which god it's the symbol of (Mask, the Lord of Shadows)`,
    `A mask made of oak, when it is worn your voice becomes two octaves deeper, it can be worn backwards, making your voice two octaves higher`,
    `A ball of twine that cannot be untangled`,
    `A piece of glass that constantly reflects a rainbow`,
    `A small crab that loves you unconditionally, the crab is immortal and follows you everywhere`,
    `A silver rod that changes color with your mood`,
    `A sponge that can absorb much more liquid than it should be able to (10 gallons)`,
    `A skull that mumbles racist slurs whenever it sees an elf (DC 15 medicine to identify its dwarven shape)`,
    `A fork that will pierce anything`,
    `A foggy mirror, when cleaned returns to being foggy`,
    `A red earring that when worn allows you to speak Abyssal, but only "I don't speak Abyssal."`,
    `A mushroom that tastes of strawberry, when planted spawns an identical cap fifteen feet tall`,
    `A brass ball that constantly smells horrible, but when sleeping near it you always have pleasant dreams`,
    `A drawing of a manatee, the manatee moves within the frame`,
    `The eye of a beholder, it blinks and looks around of its own accord (DC 15 investigation to discover it has "Beauty" carved in its pupil)`,
    `A flute that sounds different for everyone that hears it`,
    `A necklace that always fits perfectly no matter who wears it`,
    `A bamboo straw that when blown into produces water (Up to 10 gallons a day)`,
    `A stone that bounces off anything, it has jagged edges`,
    `A monocle that let's you read fine text from 10ft away`,
    `A dull sword that cannot be sharpened, it produces musical notes when you swing it`,
    `A crown made from reeds that lets you talk to amphibians`,
    `A golden finch, when the command word is spoken it becomes alive (You don't know the command word)`,
    `A letter from a fiance you didn't know you had, if you drop it it'll come back to you within a week`,
    `A small vial with an insect inside, it seems very angry`,
    `An overpriced sea shell that a girl sold you on the shore, when you look at it you always smile`,
    `A box that holds the heart of a faerie queen`,
    `A bottle of black sand that is flammable`,
    `A signet ring with draconic symbols, when used to seal something in wax the symbols move`,
    `A cowl made of raven feathers, when you wear it you gain the personality of a loner`,
    `A statue of a zebra, no one can tell if it's black with white stripes or white with black stripes`,
    `An invitation to visit a jungle tribe, there is a map burned with arcane magic into the letter that's painful to read`,
    `A vial that constantly leaks honey`,
    `A fishing hook that cannot be bent`,
    `A stone shaped like a heart that makes common folk like you, if it's broken you become depressed for 1d10 days`,
    `Drift wood that smells of salt, it can be bent by hand`,
    `A teleportation circle diagram, you don't know how to use it, or where it will take you`,
    `A whistle that when blown causes you to fly 5ft backwards (3 uses per day)`,
    `A belt with a pocket that has more room than it should (Holds up a cubic foot with no weight limit)`,
    `A pouch of white sand that refills itself every day`,
    `A tiny statue of a praying mantis, staring at it for too long causes horrible visions of an impending disaster`,
    `Hand wraps that glow softly when rubbed together`,
    `The hilt of a sword that feels heavier than it should, when the command word is spoken a blade shoots from the hilt and becomes a shortsword (You don't know the command word)`,
    `A glass bottle that holds a small storm (Rain, lightning, thunder, and dark clouds, when opened the storm dissipates, but comes back the next day)`,
    `A faerie trapped in a bottle, it gazes at you seductively (It's only friendly towards you and other fae)`,
    `A book of elven text, reading it makes you sleepy`,
    `A scroll that bleeds when you open it`,
    `A small stone with a hole in the center, fragrant smoke constantly drifts out of the hole`,
    `A venus fly trap that will eat anything that fits in its mouth`,
    `A wand that when held moves about on its own accord (This movement is in time with a nearby song)`,
    `A marble that hovers three inches above your hand`,
    `A paper fan that when used produces no breeze, but will put out any non-magical fire`,
    `A crystal ball that shows you the person you love the most`,
    `A vial filled with fine white hairs, in moonlight they glow brightly`,
    `A section of leather that growls when you pick it up`,
    `A king from a chess set, he gives privileged, out-of-touch advice when asked a question`,
    `A hair brooch that makes the wearer unable to speak`,
    `A wooden doll that makes whoever looks at it uncomfortable`,
    `A hat that changes style every day`,
    `A bottle that can capture a sound when the command word is spoken, when opened it repeats this sound once (You don't know the command word)`,
    `An egg of unknown origin, you can tell it's alive, but don't know what will hatch`,
    `A puzzle box that when opened (DC 15 INT) contains two items on this list`
]