export default [
    'Cap',
    'Wizard\'s Hat',
    'Beret',
    'Circlet',
    'Belt',
    'Suspenders',
    'Boots',
    'Gloves',
    'Gauntlets',
    'Fingerless Gloves',
    'Nose Ring',
    'Amulet',
    'Bow Tie',
    'Amulet',
    'Medallion',
    'Bracers',
    'Bracelet',
    'Scarf',
    'Ring',
    'Vest',
    'Quiver',
    'Cloak',
    'Scabbard'
]