export default [
  `Speaks fast with a small lisp`,
  `Deep voice with rolling R's`,
  `Pronounces most S's like Z's`,
  `French accent`,
  `Low and grunting`,
  `High pitched and excited`,
  `Often laughs before speaking`,
  `Relaxed with a lot of content humming`,
  `Spanish accent`,
  `Scratchy and weak`,
  `Posh accent`,
  `Mostly speaks with clenched teeth`,
  `Soft and melodious`,
  `Pronounces most O's like U's`,
  `Eastern European accent`,
  `Old and thin voice`,
  `Farmer's accent`,
  `Puts emphasis on the wrong part of words`,
  `Slow speaker`,
  `Russian accent`,
  `Whispering most of the time`,
  `Yelps nervously whilst speaking`,
  `Sighs with exhaustion a lot`,
  `Frivolous and kind`,
  `Scottish accent`,
  `Uses the word 'Darling' a lot`,
  `Loud with a lot of bravado`,
  `Dutch accent`,
  `Often pauses mid-sentence to think`,
  `Australian accent`,
  `Prepubescent and boyish`,
  `Notes of animalistic growling and snarling`,
  `Smooth and feminine`,
  `Raspy`,
  `Italian accent`,
  `Excited and jittery`,
  `Warm and comforting`,
  `Middle-eastern accent`,
  `Inhaling and exhaling with a thin wheeze`,
  `Voice often breaking`,
  `Half singing most sentences`,
  `Speaks in the back of the mouth`,
  `Scandinavian accent`,
  `Speaks like royalty, uses complex vocabulary`,
  `Words like 'its' and 'is' become 'eats' and 'ease'`,
  `Vocalizes with an open throat`,
  `Skittish`,
  `Jamaican Accent`,
  `Frightful`,
  `Hard of hearing, loud`,
  `Dark and ominous tone`,
  `American accent`,
  `Smacks lips whilst talking`,
  `Monstrous and snarling`,
  `Gruff and masculine`,
  `Vocalizes in the front of the mouth`,
  `Tuts and clicks tongue a lot`,
  `Adds syllables to words to emphasize`,
  `Vocalizes with a squeezed throat`,
  `Squeaky`,
  `Pirate accent`,
  `Speaks like their tongue is numb`,
  `Classic creaky witch voice`,
  `Spits and sputters whilst talking`,
  `Thin and often mumbling`,
  `Speaks with their lower jaw jutted out`,
  `Irish accent`,
  `Soothing and warm`,
  `Keeps vowels as short as possible`,
  `Low rumbling, the words strung together`,
  `Strong lisp`,
  `Cold and demanding tone`,
  `Mid range voice`,
  `German accent`,
  `Speaks with lips slightly pursed`,
  `Speaks in third person about themselves`,
  `Relaxed voice`,
  `Sensual and smooth`,
  `Low range voice`,
  `Switches between two types of voices`,
  `Mumbles notes to self in between sentences`,
  `Indian accent`,
  `Aggressive tone`,
  `Draws out most vowels when speaking`,
  `Nasal tone`,
  `High range voice`,
  `Often pronounces difficult words wrong`,
  `Forgets to breathe when speaking`,
  `Hollow sounding voice`,
  `Switches between three voices`,
  `Uses sign language`,
  `Slurs words`,
  `Voice like an elderly individual`,
  `Speaks as if they have a cold/blocked nose`,
  `Uses figure of speech often`,
  `Often spits out words with contempt`, 
  `Uses the words/sounds 'uh' and 'uhm' a lot`,
  `Rhymes sentences often`,
  `Sore throat, coughing a lot`,
  `High pitched and slightly raspy`,
]
